import { AgentInfo } from "./types";

export const AGENTS_LIST: AgentInfo[] = [
  // 1. Discovery & Literature
  {
    id: "academic_chat",
    title: "Conversational Research AI",
    description: "Converse, brainstorm, write code, hypothesize, and refine research concepts with scholarly depth and citations.",
    icon: "MessageSquareText",
    category: "Discovery & Literature",
    placeholder: "Ask any question, brainstorm research ideas, or discuss theories...",
    suggestedPrompts: [
      "What are the main theoretical differences between transformers and state-space models?",
      "How to design an unbiased sample for evaluating LLM reasoning benchmarks?",
      "Explain the causal mechanisms behind transfer learning in low-resource settings.",
    ],
  },
  {
    id: "find_papers",
    title: "480M+ Paper Discovery",
    description: "Query OpenAlex, Semantic Scholar, arXiv, PubMed, Europe PMC, and Crossref with direct DOI & PDF links.",
    icon: "Search",
    category: "Discovery & Literature",
    placeholder: "Enter research keywords, topic, or paper titles to find live papers...",
    suggestedPrompts: [
      "Quantum machine learning algorithms for drug discovery",
      "Retrieval augmented generation hallucination reduction",
      "Graph neural networks for social network anomaly detection",
    ],
  },
  {
    id: "literature_overview",
    title: "Systematic Literature Review",
    description: "Synthesize empirical papers into a publication-ready structured literature review with thematic matrices.",
    icon: "Layers",
    category: "Discovery & Literature",
    placeholder: "Specify the synthesis angle or focus for your literature review...",
    suggestedPrompts: [
      "Synthesize the state of research on reinforcement learning from human feedback",
      "Map out the major paradigms in federated learning privacy preservation",
      "Create a comparative overview of zero-shot vs few-shot prompt engineering",
    ],
  },
  {
    id: "find_citations",
    title: "Citation & BibTeX Manager",
    description: "Format sources into APA 7th, MLA 9th, Chicago 17th, IEEE, and generate clean BibTeX entries for Overleaf/Zotero.",
    icon: "FileText",
    category: "Discovery & Literature",
    placeholder: "Enter papers or topic to generate formatted academic citations...",
    suggestedPrompts: [
      "Generate BibTeX citations for foundational transformer and attention papers",
      "Format citations in APA 7th for CRISPR Cas9 landmark publications",
      "Export IEEE citations for federated learning benchmark studies",
    ],
  },
  {
    id: "bibliometrics_map",
    title: "Scientometrics & Citation Mapper",
    description: "Map author h-indices, co-citation clusters, journal impact trajectories, and geographic collaboration hubs.",
    icon: "Network",
    category: "Discovery & Literature",
    placeholder: "Enter an author, institution, or field to map scientometric trends...",
    suggestedPrompts: [
      "Map the co-citation cluster of Demis Hassabis and AlphaFold structural biology",
      "Analyze the citation velocity of DeepSeek-V3 vs Llama 3 across 2024-2025",
    ],
  },
  {
    id: "podcast_summarizer",
    title: "Academic Podcast & Speech Forge",
    description: "Convert dense manuscripts into 10-minute scientific audio scripts, keynote lectures, or conference elevator pitches.",
    icon: "Mic",
    category: "Discovery & Literature",
    placeholder: "Paste paper abstract or topic to generate an engaging science podcast script...",
    suggestedPrompts: [
      "Generate an engaging 5-minute podcast episode explaining CRISPR base editing",
      "Create a conference elevator pitch for a novel graph neural network architecture",
    ],
  },

  // 2. Ideation & Hypotheses
  {
    id: "research_gaps",
    title: "Research Gap Detective",
    description: "Detect unexplored blindspots, methodology weaknesses, and high-impact publication opportunities.",
    icon: "Lightbulb",
    category: "Ideation & Hypotheses",
    placeholder: "Enter a research domain to uncover unexplored gaps...",
    suggestedPrompts: [
      "Find unexplored research gaps in multi-modal LLM reasoning benchmarks",
      "Identify methodological limitations in current zero-shot medical diagnosis models",
      "What are the missing links in quantum error mitigation for NISQ devices?",
    ],
  },
  {
    id: "research_questions",
    title: "Hypothesis & Question Architect",
    description: "Formulate FINER-compliant research questions with null and alternative hypotheses ($H_0, H_1$).",
    icon: "HelpCircle",
    category: "Ideation & Hypotheses",
    placeholder: "Enter a topic to generate publication-worthy hypotheses...",
    suggestedPrompts: [
      "Formulate quantitative hypotheses testing LLM context compression efficiency",
      "Create mixed-methods research questions on AI adoption in clinical radiology",
      "Develop experimental hypotheses for evaluating battery electrolyte degradation",
    ],
  },
  {
    id: "cross_disciplinary",
    title: "Interdisciplinary Hybridizer",
    description: "Synthesize concepts across distant fields (e.g. Statistical Physics $\\rightarrow$ Neural Networks, Ecology $\\rightarrow$ Macroeconomics).",
    icon: "Sparkles",
    category: "Ideation & Hypotheses",
    placeholder: "Specify two or more fields to discover hybrid cross-pollination breakthroughs...",
    suggestedPrompts: [
      "Apply statistical physics spin-glass models to deep neural network loss landscapes",
      "Combine ecological food-web network theory with systemic financial risk contagion",
    ],
  },
  {
    id: "patent_prior_art",
    title: "Patent & Prior-Art Novelty Agent",
    description: "Evaluate patentability, prior-art conflicts across USPTO/WIPO, and commercial novelty claims.",
    icon: "ShieldCheck",
    category: "Ideation & Hypotheses",
    placeholder: "Describe your invention or algorithmic method for prior-art novelty audit...",
    suggestedPrompts: [
      "Conduct a prior-art novelty check on a solid-state battery electrolyte additive",
      "Assess patentability of a novel zero-knowledge proof verification pipeline",
    ],
  },

  // 3. Biomedical & Genomics
  {
    id: "clinical_trials_consort",
    title: "Clinical Trial & CONSORT Protocol",
    description: "Design RCT protocols, eligibility criteria, blinding procedures, and CONSORT 2010 compliance checklists.",
    icon: "Stethoscope",
    category: "Biomedical & Genomics",
    placeholder: "Describe the clinical intervention and cohort to design an RCT protocol...",
    suggestedPrompts: [
      "Design a Phase-III double-blind RCT protocol for a novel GLP-1 receptor agonist",
      "Generate a CONSORT 2010 checklist and patient flow diagram for an oncology trial",
    ],
  },
  {
    id: "gwas_prs",
    title: "GWAS & Polygenic Risk Modeler",
    description: "Analyze Genome-Wide Association Studies, Manhattan plot loci, SNP effect sizes, and polygenic risk scores (PRS).",
    icon: "Dna",
    category: "Biomedical & Genomics",
    placeholder: "Enter a phenotype or genetic variant loci for GWAS synthesis...",
    suggestedPrompts: [
      "Synthesize GWAS loci associated with early-onset Alzheimer's disease",
      "Calculate polygenic risk score methodology for coronary artery disease",
    ],
  },
  {
    id: "scrna_seurat",
    title: "Single-Cell RNA-seq (Seurat/Scanpy)",
    description: "Single-cell transcriptome pipelines, UMAP clustering, marker gene differential expression, and cell annotations.",
    icon: "Activity",
    category: "Biomedical & Genomics",
    placeholder: "Enter single-cell sequencing parameters or cell-type markers...",
    suggestedPrompts: [
      "Design a Seurat v5 pipeline for tumor microenvironment single-cell RNA-seq",
      "Identify marker genes for microglial activation states in neurodegeneration",
    ],
  },
  {
    id: "alphafold_docking",
    title: "AlphaFold & Molecular Docking",
    description: "Protein-ligand binding affinity, AutoDock Vina parameters, active site catalytic pockets, and complex interfaces.",
    icon: "Crosshair",
    category: "Biomedical & Genomics",
    placeholder: "Enter target protein or ligand SMILES for docking analysis...",
    suggestedPrompts: [
      "Analyze the binding pocket interaction between KRAS G12D and small molecule inhibitors",
      "Configure AutoDock Vina grid box parameters for SARS-CoV-2 main protease (Mpro)",
    ],
  },
  {
    id: "crispr_off_target",
    title: "CRISPR gRNA Off-Target Auditor",
    description: "Cas9/Cas12a PAM specificity, CFD off-target cleavage scores, base editing window, and prime editing flap design.",
    icon: "Scissors",
    category: "Biomedical & Genomics",
    placeholder: "Enter 20-nt target sequence or gene exon for gRNA specificity audit...",
    suggestedPrompts: [
      "Design high-specificity Cas9 gRNAs targeting Exon 3 of human PCSK9",
      "Evaluate off-target cleavage risks using CFD matrix for prime editing pegRNA",
    ],
  },
  {
    id: "synbio_circuits",
    title: "Synthetic Biology Genetic Circuits",
    description: "SBOL biological parts, logic gates (AND, NOR, Toggle Switch), plasmid promoters, and transcriptional regulators.",
    icon: "Cpu",
    category: "Biomedical & Genomics",
    placeholder: "Describe the desired synthetic biological logic or biosensor function...",
    suggestedPrompts: [
      "Design a genetic toggle switch circuit with LacI and TetR repressors",
      "Construct an AND gate biosensor detecting arsenic and hypoxia in bacteria",
    ],
  },
  {
    id: "microbiome_metagenomics",
    title: "Microbiome & 16S Metagenomics",
    description: "Alpha/Beta diversity ($Shannon, Bray-Curtis$), taxonomic OTU abundance, and functional PICRUSt2 pathway mapping.",
    icon: "Globe",
    category: "Biomedical & Genomics",
    placeholder: "Enter microbiome cohort or sequencing data parameters...",
    suggestedPrompts: [
      "Compare gut microbiome alpha-diversity differences between healthy and IBD cohorts",
      "Perform PICRUSt2 functional metabolic pathway enrichment on 16S rRNA OTUs",
    ],
  },
  {
    id: "bioethics_irb",
    title: "Bioethics & IRB Ethics Protocol",
    description: "Institutional Review Board (IRB) ethics application, informed consent, participant risk mitigation, and HIPAA/GDPR compliance.",
    icon: "Shield",
    category: "Biomedical & Genomics",
    placeholder: "Describe your human/animal study protocol for IRB ethics review...",
    suggestedPrompts: [
      "Draft an IRB ethics protocol for a study collecting biometric EEG and eye-tracking data",
      "Create an informed consent template compliant with the revised Common Rule",
    ],
  },
  {
    id: "animal_arrive",
    title: "Animal Research ARRIVE 2.0 Auditor",
    description: "In-vivo experimental design, animal group sample size power, housing condition reporting, and ARRIVE compliance.",
    icon: "CheckSquare",
    category: "Biomedical & Genomics",
    placeholder: "Enter animal study design for ARRIVE 2.0 checklist evaluation...",
    suggestedPrompts: [
      "Audit a murine behavioral study protocol against ARRIVE 2.0 Essential 10 guidelines",
    ],
  },

  // 4. Physics, Chemistry & Engineering
  {
    id: "quantum_qiskit",
    title: "Quantum Circuit & Qiskit Architect",
    description: "Quantum algorithms (VQE, QAOA, Shor, Grover), Clifford gates, quantum error mitigation, and state fidelity calculations.",
    icon: "Sparkles",
    category: "Physics, Chemistry & Engineering",
    placeholder: "Specify a quantum algorithm or Hamiltonian to design a Qiskit circuit...",
    suggestedPrompts: [
      "Construct a Variational Quantum Eigensolver (VQE) circuit for Hydrogen molecule ($H_2$)",
      "Design a Quantum Approximate Optimization Algorithm (QAOA) for Max-Cut on graphs",
    ],
  },
  {
    id: "condensed_dft",
    title: "Condensed Matter DFT (VASP/ESPRESSO)",
    description: "Density Functional Theory calculations, exchange-correlation functionals (PBE/HSE06), K-points, and bandgap structures.",
    icon: "Box",
    category: "Physics, Chemistry & Engineering",
    placeholder: "Enter crystal lattice or material composition for DFT modeling...",
    suggestedPrompts: [
      "Generate VASP INCAR and KPOINTS parameters for band structure of 2D $\\text{MoS}_2$",
      "Calculate projected density of states (PDOS) for transition metal oxide catalysts",
    ],
  },
  {
    id: "astrophysics_spectral",
    title: "Astrophysics Spectral & Cosmology Agent",
    description: "JWST/Hubble spectral energy distributions (SED), Doppler redshift ($z$), emission line fitting, and dark matter halos.",
    icon: "Eye",
    category: "Physics, Chemistry & Engineering",
    placeholder: "Enter astronomical coordinates, redshift, or spectral wavelengths...",
    suggestedPrompts: [
      "Model the spectral energy distribution (SED) of a high-redshift galaxy ($z = 7.5$)",
      "Calculate gravitational lensing mass profile of an elliptical galaxy cluster",
    ],
  },
  {
    id: "cfd_openfoam",
    title: "CFD & Navier-Stokes OpenFOAM Modeler",
    description: "Computational fluid dynamics, mesh generation, Reynolds numbers, boundary layers, and turbulence modeling ($k-\\omega\\text{ SST}$).",
    icon: "Wind",
    category: "Physics, Chemistry & Engineering",
    placeholder: "Describe the fluid flow geometry and boundary conditions...",
    suggestedPrompts: [
      "Configure OpenFOAM blockMesh and boundary conditions for NACA 0012 airfoil flow",
      "Calculate boundary layer thickness and $y^+$ values for supersonic turbulent flow",
    ],
  },
  {
    id: "gaafet_tcad",
    title: "Semiconductor 2nm GAAFET & TCAD",
    description: "Gate-all-around nanosheet electrostatics, subthreshold swing ($SS$), drain-induced barrier lowering ($DIBL$), and FinFET scaling.",
    icon: "Zap",
    category: "Physics, Chemistry & Engineering",
    placeholder: "Enter nanosheet dimensions and doping concentrations for TCAD modeling...",
    suggestedPrompts: [
      "Optimize electrostatic subthreshold swing in a 3-stack GAAFET nanosheet architecture",
      "Model quantum confinement effects in sub-3nm silicon channel transistors",
    ],
  },
  {
    id: "robotics_ros2",
    title: "Robotics ROS2 Kinematics & Motion Planner",
    description: "URDF robot kinematics, forward/inverse kinematic transformations (DH parameters), and MoveIt path planning.",
    icon: "Cog",
    category: "Physics, Chemistry & Engineering",
    placeholder: "Describe the robot manipulator DOFs and trajectory goals...",
    suggestedPrompts: [
      "Derive Denavit-Hartenberg (DH) parameters for a 6-DOF robotic arm manipulator",
      "Generate a ROS2 MoveIt C++ node for trajectory execution with collision avoidance",
    ],
  },
  {
    id: "battery_electrolyte",
    title: "Solid-State Battery & Electrolyte Chemist",
    description: "Solid electrolyte interphase (SEI) stability, lithium dendrite suppression, ionic conductivity ($\sigma$), and cyclic voltammetry.",
    icon: "BatteryCharging",
    category: "Physics, Chemistry & Engineering",
    placeholder: "Enter battery cathode/anode chemistry and electrolyte composition...",
    suggestedPrompts: [
      "Model ionic conductivity and electrochemical stability window of LLZO solid electrolytes",
      "Analyze cyclic voltammetry redox peaks for high-nickel NMC811 cathode degradation",
    ],
  },
  {
    id: "green_hydrogen",
    title: "Green Hydrogen & Electrolyzer Catalyst",
    description: "Hydrogen Evolution (HER) & Oxygen Evolution (OER) overpotentials ($\eta$), Tafel slopes ($mV/dec$), and PEM electrolyzer efficiency.",
    icon: "Flame",
    category: "Physics, Chemistry & Engineering",
    placeholder: "Enter electrocatalyst composition and alkaline/PEM cell conditions...",
    suggestedPrompts: [
      "Calculate overpotential and Tafel slope for single-atom Pt/C hydrogen evolution catalysts",
      "Design a high-efficiency membrane electrode assembly (MEA) for PEM water electrolysis",
    ],
  },
  {
    id: "retrosynthesis_chemist",
    title: "Organic Retrosynthesis & Reaction Planner",
    description: "Retrosynthetic disconnection approach, protecting group strategies, SMILES notation, and catalyst optimization.",
    icon: "FlaskConical",
    category: "Physics, Chemistry & Engineering",
    placeholder: "Paste target molecule SMILES or IUPAC name for retrosynthetic disconnection...",
    suggestedPrompts: [
      "Propose a 5-step enantioselective retrosynthetic pathway for complex natural alkaloids",
      "Optimize Suzuki-Miyaura cross-coupling conditions for sterically hindered biaryls",
    ],
  },
  {
    id: "civil_earthquake_fem",
    title: "Structural Earthquake & FEM Modeler",
    description: "Nonlinear response history analysis (NLRHA), seismic base isolation, modal response spectra, and concrete stress-strain curves.",
    icon: "Building",
    category: "Physics, Chemistry & Engineering",
    placeholder: "Enter structural geometry and seismic design response spectrum...",
    suggestedPrompts: [
      "Model seismic demand on a 20-story buckling-restrained braced frame building",
    ],
  },
  {
    id: "telecom_6g",
    title: "6G Sub-THz & Massive MIMO Telecommunications",
    description: "Reconfigurable Intelligent Surfaces (RIS), beamforming precoding matrices, Sub-THz path loss, and Shannon channel capacity.",
    icon: "Radio",
    category: "Physics, Chemistry & Engineering",
    placeholder: "Enter frequency band (e.g. 140 GHz) and antenna array configuration...",
    suggestedPrompts: [
      "Optimize hybrid analog-digital beamforming for 140 GHz Sub-THz massive MIMO systems",
    ],
  },

  // 5. Economics & Quantitative Finance
  {
    id: "macro_dsge_econometrics",
    title: "Macroeconomic DSGE & Econometrics",
    description: "Dynamic Stochastic General Equilibrium (DSGE) model equations, Taylor Rule monetary shocks, and impulse response functions (IRF).",
    icon: "TrendingUp",
    category: "Economics & Quantitative Finance",
    placeholder: "Specify the macroeconomic policy shock or monetary rule equations...",
    suggestedPrompts: [
      "Derive first-order conditions for a New Keynesian DSGE model with sticky prices (Calvo)",
      "Compute impulse response functions (IRF) for an unexpected central bank interest rate hike",
    ],
  },
  {
    id: "econometric_iv_gmm",
    title: "Instrumental Variables & 2SLS / GMM",
    description: "Endogeneity correction, Two-Stage Least Squares (2SLS), Cragg-Donald weak instrument $F$-tests, and Hansen $J$ overid tests.",
    icon: "BarChart3",
    category: "Economics & Quantitative Finance",
    placeholder: "Specify your endogenous regressor and candidate instrumental variables...",
    suggestedPrompts: [
      "Evaluate instrument validity and exclusion restrictions using 2SLS in Stata/R",
      "Formulate moment conditions for Generalized Method of Moments (GMM) estimation",
    ],
  },
  {
    id: "did_staggered",
    title: "Difference-in-Differences (DiD) Auditor",
    description: "Callaway-Sant'Anna & Sun-Abraham staggered DiD estimators, parallel trends pre-testing, and event-study plots.",
    icon: "Calendar",
    category: "Economics & Quantitative Finance",
    placeholder: "Describe the policy rollout timing and treatment/control cohorts...",
    suggestedPrompts: [
      "Implement Callaway and Sant'Anna (2021) staggered DiD estimator with dynamic treatment effects",
      "Test parallel trends assumptions using an event-study regression with lead/lag coefficients",
    ],
  },
  {
    id: "market_microstructure",
    title: "High-Frequency Market Microstructure",
    description: "Limit Order Book (LOB) dynamics, Kyle’s Lambda ($\lambda$), Amihud illiquidity, and order flow toxicity ($VPIN$).",
    icon: "DollarSign",
    category: "Economics & Quantitative Finance",
    placeholder: "Enter tick-level dataset specifications or price impact parameters...",
    suggestedPrompts: [
      "Derive Kyle's Lambda price impact parameter from high-frequency order book flow",
      "Calculate Volume-Synchronized Probability of Toxicity (VPIN) during flash crashes",
    ],
  },
  {
    id: "game_theory_mechanism",
    title: "Game Theory & Mechanism Design",
    description: "Bayesian Nash Equilibria, Vickrey-Clarke-Groves (VCG) truthful auctions, and incentive-compatible contract design.",
    icon: "Award",
    category: "Economics & Quantitative Finance",
    placeholder: "Specify the player utility functions and information structure...",
    suggestedPrompts: [
      "Design a truthful multi-item spectrum auction mechanism satisfying VCG efficiency",
      "Find the subgame perfect Nash equilibrium in an asymmetric information bargaining game",
    ],
  },
  {
    id: "behavioral_nudge",
    title: "Behavioral Economics Nudge Modeler",
    description: "Hyperbolic discounting parameters ($\beta, \delta$), prospect theory probability weighting, and choice architecture nudges.",
    icon: "PieChart",
    category: "Economics & Quantitative Finance",
    placeholder: "Describe the behavioral choice scenario and bias parameters...",
    suggestedPrompts: [
      "Model quasi-hyperbolic discounting ($\beta-\\delta$) in retirement savings commitment devices",
      "Design an optimal default nudge architecture to maximize organ donation enrollment",
    ],
  },
  {
    id: "carbon_tax_econ",
    title: "Carbon Tax & Environmental Economics",
    description: "Social Cost of Carbon ($SCC$), cap-and-trade carbon credit equilibria, and marginal abatement cost curves (MACC).",
    icon: "Trees",
    category: "Economics & Quantitative Finance",
    placeholder: "Enter emissions reduction targets and regional abatement cost data...",
    suggestedPrompts: [
      "Compute optimal carbon tax trajectory balancing GDP growth and 1.5C climate targets",
    ],
  },
  {
    id: "asset_pricing_fama",
    title: "Empirical Asset Pricing & Factor Zoo",
    description: "Fama-French 5-Factor regressions, Carhart momentum, GRS test for factor spanning, and risk-adjusted alpha ($\alpha$).",
    icon: "LineChart",
    category: "Economics & Quantitative Finance",
    placeholder: "Enter portfolio return series and candidate pricing factors...",
    suggestedPrompts: [
      "Run Fama-MacBeth two-pass cross-sectional regressions to estimate factor risk premia",
    ],
  },
  {
    id: "labor_automation",
    title: "Labor Economics & AI Automation",
    description: "Task-based labor displacement frameworks (Acemoglu-Restrepo), wage elasticity, and skill-biased technological change.",
    icon: "Briefcase",
    category: "Economics & Quantitative Finance",
    placeholder: "Specify the industry sector and technological displacement scenario...",
    suggestedPrompts: [
      "Model the task-displacement vs reinstatement effects of Generative AI on cognitive labor",
    ],
  },
  {
    id: "corporate_governance",
    title: "Corporate Governance & Executive Incentives",
    description: "Principal-agent moral hazard proofs, CEO compensation vega/delta, and shareholder voting power (Banzhaf index).",
    icon: "Scale",
    category: "Economics & Quantitative Finance",
    placeholder: "Describe the executive contract or shareholder voting structure...",
    suggestedPrompts: [
      "Formulate an optimal executive compensation contract with unobservable effort and risk aversion",
    ],
  },

  // 6. Psychology, Law & Social Sciences
  {
    id: "fmri_spm_glm",
    title: "fMRI Neuroimaging (SPM / FSL GLM)",
    description: "BOLD contrast General Linear Models, motion artifact regressor matrices, and Family-Wise Error (FWE) cluster corrections.",
    icon: "Brain",
    category: "Psychology, Law & Social Sciences",
    placeholder: "Enter fMRI paradigm conditions and hemodynamic response parameters...",
    suggestedPrompts: [
      "Configure a first-level SPM12 design matrix for an event-related working memory fMRI task",
      "Apply Gaussian Random Field Theory for family-wise error (FWE) cluster-level correction",
    ],
  },
  {
    id: "eeg_erp",
    title: "EEG / MEG Event-Related Potential (ERP)",
    description: "P300, N400, MMN cognitive wave extraction, baseline normalization, and time-frequency Morlet wavelet transforms.",
    icon: "Activity",
    category: "Psychology, Law & Social Sciences",
    placeholder: "Enter EEG electrode montage and experimental trigger conditions...",
    suggestedPrompts: [
      "Analyze N400 semantic violation amplitudes across centroparietal electrode sites",
      "Perform Morlet wavelet time-frequency decomposition on frontal theta oscillations during cognitive control",
    ],
  },
  {
    id: "irac_legal_case",
    title: "Legal Jurisprudence & IRAC Reasoner",
    description: "IRAC framework (Issue, Rule, Application, Conclusion) with statutory interpretation and judicial case precedents.",
    icon: "Scale",
    category: "Psychology, Law & Social Sciences",
    placeholder: "State the legal controversy or statutory clause for IRAC case analysis...",
    suggestedPrompts: [
      "Draft an IRAC legal analysis on fair use doctrine regarding AI model training on copyrighted code",
      "Analyze Fourth Amendment constitutional jurisprudence regarding warrantless cell-site location data",
    ],
  },
  {
    id: "eu_ai_act_compliance",
    title: "EU AI Act & Algorithmic Auditor",
    description: "High-risk AI conformity assessments, fundamental rights impact assessment, and training data transparency disclosures.",
    icon: "FileCheck",
    category: "Psychology, Law & Social Sciences",
    placeholder: "Describe the AI system architecture and deployment context for EU AI Act audit...",
    suggestedPrompts: [
      "Audit a biometric medical diagnosis AI system against EU AI Act High-Risk Annex III obligations",
      "Create a fundamental rights impact assessment (FRIA) for an automated credit-scoring model",
    ],
  },
  {
    id: "geopolitical_deterrence",
    title: "Geopolitical Deterrence & Conflict Modeler",
    description: "Crisis escalation decision trees, game-theoretic nuclear deterrence, and international sanctions economic impact matrices.",
    icon: "Globe",
    category: "Psychology, Law & Social Sciences",
    placeholder: "Specify the geopolitical state actors and strategic leverage points...",
    suggestedPrompts: [
      "Model strategic escalation dynamics in a multi-polar cyberwarfare deterrence scenario",
    ],
  },
  {
    id: "computational_linguistics",
    title: "Computational Linguistics & Semantic Drift",
    description: "Diachronic word embeddings, semantic shift detection in historical corpora, and distributional formal semantics.",
    icon: "BookOpen",
    category: "Psychology, Law & Social Sciences",
    placeholder: "Enter historical corpus parameters or lexical terms for semantic drift analysis...",
    suggestedPrompts: [
      "Track diachronic semantic shift of political keywords using temporal word embeddings",
    ],
  },
  {
    id: "philosophy_consciousness",
    title: "Philosophy of Mind & IIT Consciousness",
    description: "Integrated Information Theory ($\Phi$) concepts, Global Workspace Theory, Chalmers Hard Problem, and subjective qualia.",
    icon: "Sparkles",
    category: "Psychology, Law & Social Sciences",
    placeholder: "Formulate philosophical propositions on consciousness and machine cognition...",
    suggestedPrompts: [
      "Critically evaluate Integrated Information Theory (IIT 4.0) vs Global Neuronal Workspace Theory",
      "Formulate a philosophical argument regarding the moral status of sentient autonomous AI systems",
    ],
  },

  // 7. Statistics & Methodology
  {
    id: "analysis_foundry",
    title: "Analysis Foundry & Statistical Strategist",
    description: "Research design blueprints, variable operationalization, sample size calculations, and threat-to-validity audits.",
    icon: "Cpu",
    category: "Statistics & Methodology",
    placeholder: "Describe your empirical study to generate a statistical methodology blueprint...",
    suggestedPrompts: [
      "Design a statistical analysis plan for a 2x3 factorial quasi-experiment",
      "Calculate required sample size for detecting a medium effect ($f^2 = 0.15$) with 80% power",
      "Specify control variables and regression equations for an observational panel study",
    ],
  },
  {
    id: "power_analyzer",
    title: "G*Power & Sample Size Calculator",
    description: "Statistical power calculations ($1 - \\beta = 0.80$, $\\alpha = 0.05$), Cohen's $d/f^2$ effect size estimation for ANOVA, SEM, and regression.",
    icon: "Percent",
    category: "Statistics & Methodology",
    placeholder: "Enter statistical test type and desired effect size for sample size calculation...",
    suggestedPrompts: [
      "Calculate minimum sample size for a repeated-measures ANOVA with 3 groups and 4 timepoints",
      "Determine sample size required for Structural Equation Modeling (SEM) using RMSEA fit thresholds",
    ],
  },
  {
    id: "meta_effect_size",
    title: "Meta-Analysis Effect Size Converter",
    description: "Convert between Cohen's $d$, Hedges' $g$, Odds Ratios ($OR$), Relative Risk ($RR$), and Pearson $r$ with standard errors.",
    icon: "Calculator",
    category: "Statistics & Methodology",
    placeholder: "Enter effect size values (e.g., OR = 2.4, N = 400) for conversion...",
    suggestedPrompts: [
      "Convert an Odds Ratio of 2.15 with 95% CI [1.45, 3.18] to standardized mean difference (Cohen's d)",
      "Calculate pooled effect size and heterogeneity ($I^2$) across 5 clinical studies",
    ],
  },
  {
    id: "cochrane_rob2",
    title: "Cochrane RoB-2 Risk of Bias Assessor",
    description: "Assess randomized trial bias across randomization, intervention deviations, missing data, outcome measurement, and reporting.",
    icon: "ShieldAlert",
    category: "Statistics & Methodology",
    placeholder: "Enter study methodology details for Cochrane RoB-2 risk of bias evaluation...",
    suggestedPrompts: [
      "Perform a Cochrane RoB-2 risk of bias assessment on a double-blind surgical trial",
    ],
  },
  {
    id: "grade_certainty",
    title: "GRADE Evidence Certainty Evaluator",
    description: "Systematic review evidence grading (High, Moderate, Low, Very Low) across risk of bias, inconsistency, indirectness, and imprecision.",
    icon: "Award",
    category: "Statistics & Methodology",
    placeholder: "Enter meta-analysis outcomes for GRADE certainty scoring...",
    suggestedPrompts: [
      "Generate a GRADE Summary of Findings table for an immunotherapy meta-analysis",
    ],
  },
  {
    id: "psychometric_validator",
    title: "Psychometric Survey & Scale Validator",
    description: "Likert survey construct validation, Cronbach's Alpha ($\alpha$), Exploratory Factor Analysis (EFA), and Confirmatory Factor Analysis (CFA).",
    icon: "CheckCircle",
    category: "Statistics & Methodology",
    placeholder: "Enter survey items and constructs for psychometric reliability testing...",
    suggestedPrompts: [
      "Validate construct reliability and convergent validity for a 15-item technology adoption scale",
      "Generate Mplus/R lavaan syntax for Confirmatory Factor Analysis (CFA) with fit indices (CFI, TLI, RMSEA)",
    ],
  },
  {
    id: "theorem_prover",
    title: "Mathematical Theorem Prover",
    description: "Formal mathematical proofs, lemma decomposition, Lean/Coq verification syntax, and algebraic step-by-step derivations.",
    icon: "Binary",
    category: "Statistics & Methodology",
    placeholder: "State a mathematical theorem or conjecture for step-by-step formal derivation...",
    suggestedPrompts: [
      "Derive a formal step-by-step proof of the Gauss-Bonnet theorem in differential geometry",
      "Write a Lean 4 formal proof skeleton for the irrationality of $\\sqrt{2}$",
    ],
  },
  {
    id: "data_extraction",
    title: "PRISMA Data Extraction Matrix",
    description: "Extract structured academic variables into a standardized PRISMA tabular layout ready for CSV/Excel export.",
    icon: "FileSpreadsheet",
    category: "Statistics & Methodology",
    placeholder: "Specify variables to extract from research papers...",
    suggestedPrompts: [
      "Extract sample sizes, effect sizes, and primary outcomes from these clinical papers",
      "Build a structured PRISMA data matrix comparing deep learning architectures on ImageNet",
    ],
  },
  {
    id: "claim_evidence",
    title: "Claim & Evidence Verifier",
    description: "Cross-check empirical assertions against peer-reviewed literature with confidence metrics and citations.",
    icon: "CheckCircle2",
    category: "Statistics & Methodology",
    placeholder: "Enter an empirical assertion or scientific claim to verify against literature...",
    suggestedPrompts: [
      "Verify whether deep learning models reliably outperform linear baselines in tabular data",
      "Evaluate the empirical consensus on microplastics crossing the blood-brain barrier",
    ],
  },
  {
    id: "hallucination_checker",
    title: "Academic Integrity Auditor",
    description: "Scan manuscripts for fabricated DOIs, hallucinated stats, misattributed quotes, and citation integrity.",
    icon: "ShieldCheck",
    category: "Statistics & Methodology",
    placeholder: "Paste text or claims to audit against ground-truth academic registries...",
    suggestedPrompts: [
      "Audit this literature review section for citation veracity and hallucinated DOI references",
    ],
  },
  {
    id: "pytorch_flashattention",
    title: "PyTorch FlashAttention & Kernel Optimizer",
    description: "FlashAttention-2 Triton kernels, KV cache memory footprint reduction, LoRA parameter efficiency, and GPU throughput optimization.",
    icon: "Flame",
    category: "Statistics & Methodology",
    placeholder: "Paste PyTorch model layer or CUDA memory bottleneck for kernel optimization...",
    suggestedPrompts: [
      "Implement a custom PyTorch Multi-Head Latent Attention (MLA) layer with KV cache compression",
      "Optimize a transformer forward pass with FlashAttention-2 and fused rotary position embeddings (RoPE)",
    ],
  },
  {
    id: "dpo_rlhf",
    title: "Direct Preference Optimization (DPO/RLHF)",
    description: "Bradley-Terry reward model formulation, DPO objective loss gradients, and reference policy KL divergence regularizers.",
    icon: "Target",
    category: "Statistics & Methodology",
    placeholder: "Enter preference dataset structure or loss function parameters...",
    suggestedPrompts: [
      "Derive the analytical gradient of the Direct Preference Optimization (DPO) loss function",
      "Formulate an alignment objective combining DPO with verifiable rule-based reward signals",
    ],
  },

  // 8. Editorial, Grants & Publishing
  {
    id: "grant_architect",
    title: "Grant & Funding Proposal Architect",
    description: "NSF, NIH, Horizon Europe, and ERC grant proposals, Specific Aims pages, budget justifications, and broader impacts.",
    icon: "DollarSign",
    category: "Editorial, Grants & Publishing",
    placeholder: "Enter your research idea to draft a complete NIH/NSF Specific Aims page...",
    suggestedPrompts: [
      "Draft a 1-page NIH R01 Specific Aims page on AI-guided cancer immunotherapy",
      "Write an NSF CAREER broader impacts section for a quantum computing research project",
    ],
  },
  {
    id: "latex_compiler",
    title: "LaTeX & Overleaf Manuscript Writer",
    description: "Generate publication-grade LaTeX (.tex) code, math environments, subfigures, tables, and .bib files ready for Overleaf.",
    icon: "Code",
    category: "Editorial, Grants & Publishing",
    placeholder: "Specify paper section or equations to generate clean LaTeX manuscript code...",
    suggestedPrompts: [
      "Generate an IEEE conference LaTeX template with multi-column equations and subfigures",
      "Convert this literature review into a formatted LaTeX manuscript with BibTeX citations",
    ],
  },
  {
    id: "reproducible_code",
    title: "Reproducible Code & Experiment Generator",
    description: "Generate fully functional Python/PyTorch/R scripts, Jupyter notebooks, and synthetic data loaders to replicate experiments.",
    icon: "Terminal",
    category: "Editorial, Grants & Publishing",
    placeholder: "Describe the algorithm or statistical model to generate reproducible Python code...",
    suggestedPrompts: [
      "Write a complete PyTorch training script for training a Transformer from scratch on synthetic data",
      "Generate an R script running a mixed-effects logistic regression with forest plot visualization",
    ],
  },
  {
    id: "journal_rebuttal",
    title: "Journal Rebuttal & Editorial Strategist",
    description: "Transform harsh reviewer critiques into polite, persuasive, point-by-point rebuttal letters with evidence citations.",
    icon: "MessageSquare",
    category: "Editorial, Grants & Publishing",
    placeholder: "Paste reviewer comments to generate a point-by-point rebuttal letter...",
    suggestedPrompts: [
      "Draft a respectful rebuttal responding to Reviewer 2 demanding additional ablation experiments",
      "Write a point-by-point response letter addressing theoretical novelty critiques from an associate editor",
    ],
  },
  {
    id: "mock_peer_review",
    title: "Mock Peer Review Studio",
    description: "Simulate rigorous editorial board reviews: Reviewer 1 (Theory), Reviewer 2 (Methods), Reviewer 3 (Novelty) + Editor decision.",
    icon: "Users",
    category: "Editorial, Grants & Publishing",
    placeholder: "Paste your manuscript draft or abstract for a rigorous mock peer review...",
    suggestedPrompts: [
      "Conduct a double-blind peer review report on a novel deep reinforcement learning paper",
      "Evaluate theoretical rigor and experimental baselines for an LLM reasoning proposal",
    ],
  },
  {
    id: "journal_matcher",
    title: "Q1/Q2 Journal Matcher & Impact Finder",
    description: "Match your manuscript abstract with top Q1/Q2 SCI/SSCI journals, acceptance rates, review turnaround, and APC open access fees.",
    icon: "Target",
    category: "Editorial, Grants & Publishing",
    placeholder: "Paste your paper abstract to find matching top-tier Q1/Q2 academic journals...",
    suggestedPrompts: [
      "Recommend top 5 Q1 IEEE/ACM journals for a machine learning interpretability manuscript",
      "Find high-impact open-access journals in biomedical oncology with fast peer review turnaround",
    ],
  },
  {
    id: "poster_forge",
    title: "Conference Poster Forge Studio",
    description: "Transform research findings into a publication-ready 3-column academic conference poster blueprint with 5 themes.",
    icon: "Presentation",
    category: "Editorial, Grants & Publishing",
    placeholder: "Enter research paper to generate a 3-column conference poster layout...",
    suggestedPrompts: [
      "Generate an academic conference poster layout for a multi-agent AI research framework",
      "Create a 3-column poster blueprint for a clinical trial on mRNA vaccine efficacy",
    ],
  },
  {
    id: "phd_defense_slides",
    title: "PhD Defense & Presentation Deck Architect",
    description: "Structure 15-20 slide PhD defense / keynote presentation decks (Marp/Markdown/PowerPoint compatible).",
    icon: "Tv",
    category: "Editorial, Grants & Publishing",
    placeholder: "Enter thesis topic or paper outline to generate a PhD defense presentation deck...",
    suggestedPrompts: [
      "Generate a 20-slide PhD dissertation defense outline on quantum error mitigation",
      "Create a 15-minute conference presentation deck on diffusion models for medical imaging",
    ],
  },
  {
    id: "plagiarism_polisher",
    title: "Academic Formal Tone & Plagiarism Polisher",
    description: "Elevate informal drafts into Q1 journal-grade scholarly prose with enhanced clarity, precise vocabulary, and zero similarity.",
    icon: "PenTool",
    category: "Editorial, Grants & Publishing",
    placeholder: "Paste draft text to polish into publication-grade academic prose...",
    suggestedPrompts: [
      "Rewrite this methodology draft into formal, publication-grade academic English",
      "Elevate the vocabulary and syntactic flow of this introduction section for Nature submission",
    ],
  },
  {
    id: "scientific_figure_tikz",
    title: "Scientific Figure & TikZ Schematics",
    description: "Generate publication-grade vector schematics, biological pathway diagrams, and neural architecture figures (LaTeX TikZ / Mermaid).",
    icon: "Image",
    category: "Editorial, Grants & Publishing",
    placeholder: "Describe the system architecture or biological pathway to generate TikZ/Mermaid code...",
    suggestedPrompts: [
      "Generate a publication-grade LaTeX TikZ diagram of a Multi-Head Latent Attention network",
      "Create a Mermaid flow diagram of a CRISPR-Cas9 genome editing delivery mechanism",
    ],
  },
  {
    id: "dissertation_architect",
    title: "PhD Dissertation Chapter Architect",
    description: "Complete 5-chapter PhD dissertation blueprint with milestone timelines, word count targets, and defense rubrics.",
    icon: "BookOpen",
    category: "Editorial, Grants & Publishing",
    placeholder: "Enter your dissertation topic for a 5-chapter structural blueprint...",
    suggestedPrompts: [
      "Generate a 5-chapter PhD dissertation blueprint on autonomous multi-agent systems",
    ],
  },
  {
    id: "cover_letter_editor",
    title: "Journal Cover Letter & Editor Correspondence",
    description: "High-impact journal submission cover letters, editor inquiry emails, transfer appeals, and manuscript status inquiries.",
    icon: "Mail",
    category: "Editorial, Grants & Publishing",
    placeholder: "Enter paper title, journal name, and key findings to draft a submission cover letter...",
    suggestedPrompts: [
      "Draft a compelling cover letter to the Editor-in-Chief of Nature Machine Intelligence",
    ],
  },
  {
    id: "cv_biosketch_tenure",
    title: "NIH Biosketch & Academic Tenure Dossier",
    description: "NIH/NSF format Biographical Sketch (SciENcv compliant), H-index summary, contribution statements, and tenure dossiers.",
    icon: "FileText",
    category: "Editorial, Grants & Publishing",
    placeholder: "Enter your academic achievements and publications for a formatted NIH Biosketch...",
    suggestedPrompts: [
      "Format an NIH 5-page Biographical Sketch with personal statement and contributions to science",
    ],
  },
  {
    id: "fair_data_plan",
    title: "FAIR Data Management Plan (DMP)",
    description: "NIH and Horizon Europe compliant Data Management Plan (Findable, Accessible, Interoperable, Reusable) with repository deposits.",
    icon: "Database",
    category: "Editorial, Grants & Publishing",
    placeholder: "Describe your research dataset for an NIH/ERC compliant Data Management Plan...",
    suggestedPrompts: [
      "Create a FAIR Data Management Plan for a multi-center genomic and clinical trial dataset",
    ],
  },
  {
    id: "research_verdict",
    title: "Senior Editorial Research Verdict",
    description: "Assess novelty, feasibility, empirical rigor, ethical implications, and overall Scholarly Viability Score (1-100).",
    icon: "Award",
    category: "Editorial, Grants & Publishing",
    placeholder: "Submit your research proposal or thesis abstract for an overall editorial verdict...",
    suggestedPrompts: [
      "Evaluate the publication viability of a novel zero-shot transfer learning framework",
    ],
  },
];
