export interface AcademicDiscipline {
  id: string;
  name: string;
  icon: string;
  color: string;
  totalWorksEstimate: string;
  description: string;
  subfields: string[];
  primaryDatabases: string[];
  popularTopics: string[];
  landmarkPapersCount: number;
}

export const GLOBAL_ACADEMIC_DISCIPLINES: AcademicDiscipline[] = [
  {
    id: "cs_ai",
    name: "Computer Science & Artificial Intelligence",
    icon: "Cpu",
    color: "from-blue-500 to-indigo-600",
    totalWorksEstimate: "45M+ Works",
    description: "Deep learning, LLMs, computer vision, robotics, cybersecurity, quantum computing, and distributed architectures.",
    subfields: [
      "Large Language Models & Transformers",
      "Computer Vision & Multimodal Perception",
      "Reinforcement Learning & Robotics",
      "Quantum Computing & Quantum Algorithms",
      "Cybersecurity & Cryptography",
      "Distributed Systems & Cloud Computing",
      "Natural Language Processing (NLP)",
      "Graph Neural Networks & Geometric ML",
      "Human-Computer Interaction (HCI)",
      "Theoretical Computer Science & Complexity",
    ],
    primaryDatabases: ["arXiv", "OpenAlex", "Semantic Scholar", "Crossref", "IEEE Xplore", "ACM Digital Library"],
    popularTopics: ["DeepSeek-V3", "Attention Mechanisms", "Diffusion Models", "Agentic Workflows", "Quantum Error Correction", "LoRA Fine-tuning"],
    landmarkPapersCount: 250,
  },
  {
    id: "medicine_health",
    name: "Medicine, Oncology & Clinical Health",
    icon: "Stethoscope",
    color: "from-red-500 to-rose-600",
    totalWorksEstimate: "75M+ Works",
    description: "Clinical trials, oncology, immunology, cardiology, neurology, surgery, pharmacology, and translational therapeutics.",
    subfields: [
      "Precision Oncology & Targeted Therapy",
      "Immunology & Immunotherapy (CAR-T, Checkpoint Inhibitors)",
      "Neurology & Neurodegenerative Diseases (Alzheimer's, Parkinson's)",
      "Cardiovascular Medicine & Interventional Cardiology",
      "Infectious Diseases & Vaccine Development",
      "Pharmacology & Drug Discovery",
      "Clinical Trials & Systematic Evidence Synthesis",
      "Medical Imaging & AI Diagnostics",
      "Epidemiology & Global Public Health",
      "Surgical Innovations & Robotic Surgery",
    ],
    primaryDatabases: ["PubMed", "Europe PMC", "OpenAlex", "Crossref", "Semantic Scholar", "Cochrane Library"],
    popularTopics: ["mRNA Vaccines", "Immunotherapy", "GLP-1 Agonists", "AlphaFold Protein Diagnostics", "CRISPR Therapeutics", "CAR-T Cell Therapy"],
    landmarkPapersCount: 380,
  },
  {
    id: "biology_genomics",
    name: "Genomics, Molecular Biology & Life Sciences",
    icon: "Dna",
    color: "from-emerald-500 to-teal-600",
    totalWorksEstimate: "60M+ Works",
    description: "CRISPR gene editing, structural biology, evolutionary genomics, bioinformatics, epigenetics, and synthetic biology.",
    subfields: [
      "CRISPR-Cas9 & Base/Prime Genome Editing",
      "Structural Biology & Macromolecular Complexes",
      "Single-Cell RNA Sequencing & Spatial Transcriptomics",
      "Synthetic Biology & Metabolic Engineering",
      "Epigenetics & Chromatin Dynamics",
      "Evolutionary Biology & Population Genetics",
      "Microbiology & Human Microbiome",
      "Neurobiology & Synaptic Plasticity",
      "Plant Genetics & Agricultural Biotechnology",
      "Proteomics & Mass Spectrometry",
    ],
    primaryDatabases: ["PubMed", "Europe PMC", "OpenAlex", "bioRxiv", "Semantic Scholar", "NCBI GenBank"],
    popularTopics: ["CRISPR-Cas9", "AlphaFold 3", "Single-cell RNA-seq", "Epigenetic Clocks", "Spatial Genomics", "Microbiome-Gut-Brain Axis"],
    landmarkPapersCount: 310,
  },
  {
    id: "physics_astronomy",
    name: "Physics, Astronomy & Space Sciences",
    icon: "Sparkles",
    color: "from-violet-500 to-purple-600",
    totalWorksEstimate: "35M+ Works",
    description: "Quantum mechanics, astrophysics, cosmology, high-energy particle physics, general relativity, and plasma physics.",
    subfields: [
      "Quantum Mechanics & Quantum Information",
      "Astrophysics & Observational Cosmology (JWST, Hubble)",
      "High-Energy Particle Physics (CERN LHC, Standard Model)",
      "Condensed Matter Physics & Superconductivity",
      "General Relativity & Gravitational Waves (LIGO)",
      "Plasma Physics & Nuclear Fusion Energy (ITER)",
      "Optics, Photonics & Quantum Electrodynamics",
      "String Theory & Quantum Gravity",
      "Planetary Science & Exoplanet Discovery",
      "Nuclear Physics & Radioactivity",
    ],
    primaryDatabases: ["arXiv", "NASA ADS", "OpenAlex", "Crossref", "Semantic Scholar", "INSPIRE-HEP"],
    popularTopics: ["Gravitational Waves", "Higgs Boson", "JWST Deep Field", "High-Tc Superconductivity", "Quantum Entanglement", "Dark Matter"],
    landmarkPapersCount: 220,
  },
  {
    id: "chemistry_materials",
    name: "Chemistry, Nanotechnology & Materials Science",
    icon: "FlaskConical",
    color: "from-amber-500 to-orange-600",
    totalWorksEstimate: "40M+ Works",
    description: "Organic synthesis, 2D nanomaterials (graphene, MXenes), battery electrochemistry, MOFs, and green catalysis.",
    subfields: [
      "Solid-State Batteries & Electrochemical Energy Storage",
      "2D Materials, Graphene & Transition Metal Dichalcogenides",
      "Metal-Organic Frameworks (MOFs) & Porous Materials",
      "Organic Synthesis & Organocatalysis",
      "Green Chemistry & Carbon Capture Utilization",
      "Computational Materials Genome & DFT Modeling",
      "Polymer Chemistry & Biomaterials",
      "Nanomedicine & Targeted Drug Carriers",
      "Photocatalysis & Solar Hydrogen Production",
      "Coordination Chemistry & Supramolecular Assemblies",
    ],
    primaryDatabases: ["Crossref", "OpenAlex", "Semantic Scholar", "Materials Project", "CAS SciFinder"],
    popularTopics: ["Lithium-Metal Batteries", "MOF Carbon Capture", "Perovskite Solar Cells", "Graphene Nanoribbons", "Asymmetric Organocatalysis"],
    landmarkPapersCount: 240,
  },
  {
    id: "engineering_tech",
    name: "Engineering & Applied Technology",
    icon: "Cog",
    color: "from-cyan-500 to-blue-600",
    totalWorksEstimate: "50M+ Works",
    description: "Semiconductor microelectronics, aerospace engineering, renewable power grids, autonomous vehicles, and biomechanics.",
    subfields: [
      "Semiconductor Fabrication & Microelectronics (3nm/2nm GAAFET)",
      "Aerospace Engineering & Hypersonic Propulsion",
      "Renewable Energy Systems & Smart Grid Integration",
      "Autonomous Vehicles & Control Theory",
      "Robotics, Soft Robotics & Mechatronics",
      "Biomedical Devices & Neural Implants (Brain-Computer Interfaces)",
      "Civil & Structural Engineering Under Extreme Seismic Loads",
      "Wireless Communications (6G, Terahertz, Massive MIMO)",
      "Fluid Dynamics & Computational Aero-acoustics",
      "Additive Manufacturing & Industrial 3D Printing",
    ],
    primaryDatabases: ["IEEE Xplore", "OpenAlex", "Crossref", "arXiv", "Semantic Scholar"],
    popularTopics: ["GAAFET Semiconductors", "Solid-State Energy", "Neuralink BCIs", "6G Sub-THz", "Hypersonic Aerodynamics", "Soft Actuators"],
    landmarkPapersCount: 190,
  },
  {
    id: "economics_finance",
    name: "Economics, Quantitative Finance & Business",
    icon: "TrendingUp",
    color: "from-emerald-600 to-green-700",
    totalWorksEstimate: "25M+ Works",
    description: "Macroeconomic policy, behavioral economics, algorithmic trading, financial econometrics, game theory, and development.",
    subfields: [
      "Macroeconomic Modeling & Central Bank Monetary Policy",
      "Behavioral Economics & Choice Architecture",
      "Financial Econometrics & High-Frequency Algorithmic Trading",
      "Development Economics & Poverty Alleviation",
      "Mechanism Design, Game Theory & Market Microstructure",
      "Corporate Finance, M&A, and Governance",
      "Labor Economics & Automation Impact",
      "Environmental & Carbon Pricing Economics",
      "Trade Policy, Supply Chain Resilience & Geopolitics",
      "Empirical Asset Pricing & Risk Parity",
    ],
    primaryDatabases: ["RePEc", "SSRN", "OpenAlex", "Crossref", "Semantic Scholar", "NBER"],
    popularTopics: ["Inflation Dynamics", "Behavioral Nudges", "Difference-in-Differences Econometrics", "Carbon Tax Models", "AI Labor Displacement"],
    landmarkPapersCount: 175,
  },
  {
    id: "psychology_neuro",
    name: "Psychology, Cognitive Science & Neuroscience",
    icon: "Brain",
    color: "from-pink-500 to-rose-600",
    totalWorksEstimate: "30M+ Works",
    description: "Cognitive architectures, fMRI neuroimaging, psychometrics, memory consolidation, mental health, and decision science.",
    subfields: [
      "Cognitive Neuroscience & fMRI Brain Mapping",
      "Memory Formation, Consolidation & Retrieval Dynamics",
      "Decision Neuroscience & Heuristic Biases",
      "Clinical Psychology & Evidence-Based Psychotherapy (CBT)",
      "Psychometrics & Latent Variable Factor Analysis",
      "Developmental Psychology & Early Childhood Neuroplasticity",
      "Social Psychology & In-Group Dynamics",
      "Computational Psychiatry & Neurocomputational Modeling",
      "Consciousness & Integrated Information Theory",
      "Affective Neuroscience & Emotion Regulation",
    ],
    primaryDatabases: ["PubMed", "PsycINFO", "OpenAlex", "Europe PMC", "Crossref", "Semantic Scholar"],
    popularTopics: ["Default Mode Network", "Neuroplasticity", "Cognitive Biases (Kahneman)", "Neural Basis of Consciousness", "fMRI Connectomics"],
    landmarkPapersCount: 205,
  },
  {
    id: "social_law_policy",
    name: "Social Sciences, Law & Public Policy",
    icon: "Users",
    color: "from-amber-600 to-yellow-600",
    totalWorksEstimate: "35M+ Works",
    description: "Algorithmic governance, constitutional law, geopolitical relations, sociology of science, ethics in AI, and urban policy.",
    subfields: [
      "AI Ethics, Algorithmic Governance & Policy Regulations (EU AI Act)",
      "International Relations, Geopolitics & Conflict Resolution",
      "Constitutional Law, Jurisprudence & Human Rights",
      "Sociology of Technology & Digital Platform Monopolies",
      "Public Policy Design & Quantitative Program Evaluation",
      "Criminology, Algorithmic Risk Assessment & Justice Reform",
      "Urban Sociology & Sustainable Megacity Infrastructure",
      "Media Studies, Disinformation & Democratic Institutions",
      "Demography & Global Migration Patterns",
      "Education Policy & Computational Pedagogy",
    ],
    primaryDatabases: ["SSRN", "OpenAlex", "Crossref", "Semantic Scholar", "HeinOnline", "JSTOR"],
    popularTopics: ["EU AI Act", "Algorithmic Bias in Law", "Platform Antitrust", "Democratic Polarization", "Digital Surveillance Capitalism"],
    landmarkPapersCount: 160,
  },
  {
    id: "climate_earth",
    name: "Climate, Earth Systems & Environmental Science",
    icon: "Globe",
    color: "from-teal-500 to-emerald-600",
    totalWorksEstimate: "28M+ Works",
    description: "IPCC climate models, oceanography, carbon sequestration, extreme weather forecasting, geophysics, and hydrology.",
    subfields: [
      "Coupled Ocean-Atmosphere Climate Dynamics (IPCC CMIP6)",
      "Direct Air Capture & Geological Carbon Sequestration",
      "Renewable Energy Transitions & Hydrogen Economies",
      "Glaciology & Sea-Level Rise Projections",
      "Biodiversity Loss & Ecosystem Resilience Modeling",
      "Hydrological Cycles & Groundwater Depletion",
      "Extreme Weather Event Attribution (Hurricanes, Wildfires)",
      "Paleoclimatology & Ice Core Analysis",
      "Environmental Geochemistry & Microplastic Pollution",
      "Satellite Remote Sensing & Earth Observation (Copernicus)",
    ],
    primaryDatabases: ["OpenAlex", "Crossref", "Semantic Scholar", "NASA ADS", "Copernicus", "Europe PMC"],
    popularTopics: ["IPCC Sixth Assessment", "Tipping Points (AMOC)", "Carbon Mineralization", "GraphCast Climate AI", "Ocean Acidification"],
    landmarkPapersCount: 180,
  },
  {
    id: "mathematics_stats",
    name: "Mathematics, Statistics & Probability Theory",
    icon: "Calculator",
    color: "from-indigo-500 to-blue-700",
    totalWorksEstimate: "20M+ Works",
    description: "Algebraic geometry, number theory, high-dimensional probability, Bayesian inference, topology, and optimization.",
    subfields: [
      "High-Dimensional Probability & Random Matrix Theory",
      "Bayesian Inference & Markov Chain Monte Carlo (MCMC)",
      "Non-Convex Optimization & Stochastic Gradient Dynamics",
      "Algebraic Topology & Topological Data Analysis (TDA)",
      "Number Theory, Cryptography & Elliptic Curves",
      "Partial Differential Equations (Navier-Stokes, Reaction-Diffusion)",
      "Stochastic Calculus & Financial Derivatives",
      "Differential Geometry & Ricci Flow",
      "Combinatorics & Graph Theory",
      "Category Theory & Homotopy Type Theory",
    ],
    primaryDatabases: ["arXiv", "MathSciNet", "OpenAlex", "Crossref", "Semantic Scholar"],
    popularTopics: ["Navier-Stokes Smoothness", "Optimal Transport (Wasserstein)", "Random Matrix Theory", "TDA Mapper Algorithms", "Deep Learning Generalization Bounds"],
    landmarkPapersCount: 150,
  },
  {
    id: "philosophy_humanities",
    name: "Philosophy, Epistemology & Computational Humanities",
    icon: "BookMarked",
    color: "from-stone-500 to-neutral-700",
    totalWorksEstimate: "18M+ Works",
    description: "Philosophy of mind, epistemology of AI, formal ethics, computational linguistics, historical informatics, and aesthetics.",
    subfields: [
      "Philosophy of Mind & Machine Consciousness",
      "Epistemology & Theories of Truth in Synthetic Generative AI",
      "Normative Ethics & Alignment Problem (Value Learning)",
      "Formal Logic, Modal Logic & Automated Theorem Proving",
      "Computational Linguistics & Historical Corpus Semantics",
      "Bioethics & CRISPR Human Germline Editing",
      "Philosophy of Science & Paradigm Shifts (Kuhn, Popper)",
      "Digital Humanities & Quantitative Textual Archaeology",
      "Aesthetics & Generative AI Co-Creativity",
      "Political Philosophy & Theories of Justice (Rawls)",
    ],
    primaryDatabases: ["PhilPapers", "OpenAlex", "Crossref", "Semantic Scholar", "JSTOR"],
    popularTopics: ["Hard Problem of Consciousness", "AI Value Alignment", "Turing Test 2.0", "Epistemic Injustice", "Moral Status of Autonomous Agents"],
    landmarkPapersCount: 140,
  },
];
