import { AcademicPaper } from "./types";

export const GLOBAL_LANDMARK_PAPERS: AcademicPaper[] = [
  // 1. Computer Science & AI
  {
    id: "lm_attention_neurips_2017",
    title: "Attention Is All You Need",
    authors: ["Ashish Vaswani", "Noam Shazeer", "Niki Parmar", "Jakob Uszkoreit", "Llion Jones", "Aidan N Gomez", "Lukasz Kaiser", "Illia Polosukhin"],
    year: 2017,
    venue: "Advances in Neural Information Processing Systems (NeurIPS)",
    abstract: "The dominant sequence transduction models are based on complex recurrent or convolutional neural networks. We propose the Transformer, based solely on attention mechanisms, dispensing with recurrence entirely.",
    citationCount: 142500,
    source: "arXiv",
    doi: "10.48550/arXiv.1706.03762",
    url: "https://arxiv.org/abs/1706.03762",
    pdfUrl: "https://arxiv.org/pdf/1706.03762.pdf",
    isOpenAccess: true,
    topics: ["Transformers", "Deep Learning", "Self-Attention", "NLP"],
  },
  {
    id: "lm_deepseek_r1_2025",
    title: "DeepSeek-R1: Incentivizing Reasoning Capability in LLMs via Reinforcement Learning",
    authors: ["DeepSeek-AI", "Daya Guo", "Dejian Yang", "Haowei Zhang", "Songxuan Zou", "Y. Wu", "K. Chen"],
    year: 2025,
    venue: "arXiv Preprint (DeepSeek AI)",
    abstract: "We introduce DeepSeek-R1-Zero and DeepSeek-R1. DeepSeek-R1-Zero demonstrates that reasoning behaviors (chain-of-thought, self-reflection, verification) emerge purely through large-scale reinforcement learning without supervised fine-tuning.",
    citationCount: 4200,
    source: "arXiv",
    doi: "10.48550/arXiv.2501.12948",
    url: "https://arxiv.org/abs/2501.12948",
    pdfUrl: "https://arxiv.org/pdf/2501.12948.pdf",
    isOpenAccess: true,
    topics: ["Reasoning Models", "Reinforcement Learning", "DeepSeek", "Chain-of-Thought"],
  },
  {
    id: "lm_resnet_cvpr_2016",
    title: "Deep Residual Learning for Image Recognition",
    authors: ["Kaiming He", "Xiangyu Zhang", "Shaoqing Ren", "Jian Sun"],
    year: 2016,
    venue: "IEEE Conference on Computer Vision and Pattern Recognition (CVPR)",
    abstract: "Deeper neural networks are more difficult to train. We present a residual learning framework to ease the training of networks that are substantially deeper than those used previously.",
    citationCount: 215000,
    source: "OpenAlex",
    doi: "10.1109/CVPR.2016.90",
    url: "https://doi.org/10.1109/CVPR.2016.90",
    isOpenAccess: true,
    topics: ["Residual Networks", "Computer Vision", "Deep Learning", "ImageNet"],
  },

  // 2. Medicine, Oncology & Clinical Health
  {
    id: "lm_cancer_hallmarks_cell",
    title: "Hallmarks of Cancer: The Next Generation",
    authors: ["Douglas Hanahan", "Robert A. Weinberg"],
    year: 2011,
    venue: "Cell",
    abstract: "The hallmarks of cancer comprise six biological capabilities acquired during the multistep development of human tumors. We incorporate two emerging hallmarks: reprogramming of energy metabolism and evading immune destruction.",
    citationCount: 68900,
    source: "PubMed",
    doi: "10.1016/j.cell.2011.02.013",
    url: "https://doi.org/10.1016/j.cell.2011.02.013",
    isOpenAccess: true,
    topics: ["Oncology", "Cancer Biology", "Immunotherapy", "Metastasis"],
  },
  {
    id: "lm_mrna_vaccines_nature_2021",
    title: "Safety and Efficacy of the BNT162b2 mRNA Covid-19 Vaccine",
    authors: ["Fernando P. Polack", "Stephen J. Thomas", "Nicholas Kitchin", "Judith Absalon", "Ugur Sahin", "Ozgur Tuneci"],
    year: 2020,
    venue: "New England Journal of Medicine (NEJM)",
    abstract: "A two-dose regimen of BNT162b2 (30 ug per dose, given 21 days apart) conferred 95% protection against Covid-19 in persons 16 years of age or older in a multinational, placebo-controlled, randomized phase 3 trial.",
    citationCount: 18400,
    source: "Europe PMC",
    doi: "10.1056/NEJMoa2034577",
    url: "https://doi.org/10.1056/NEJMoa2034577",
    isOpenAccess: true,
    topics: ["mRNA Vaccines", "Clinical Trial", "Immunology", "Infectious Diseases"],
  },

  // 3. Biology & Genomics
  {
    id: "lm_crispr_science_2012",
    title: "A Programmable Dual-RNA-Guided DNA Endonuclease in Adaptive Bacterial Immunity",
    authors: ["Martin Jinek", "Krzysztof Chylinski", "Ines Fonfara", "Michael Hauer", "Jennifer A. Doudna", "Emmanuelle Charpentier"],
    year: 2012,
    venue: "Science",
    abstract: "Clustered regularly interspaced short palindromic repeats (CRISPR)/Cas systems provide adaptive immunity in bacteria. Here we show that the Cas9 endonuclease is guided by dual-RNA molecules to introduce double-stranded breaks in target DNA.",
    citationCount: 22400,
    source: "Crossref",
    doi: "10.1126/science.1225829",
    url: "https://doi.org/10.1126/science.1225829",
    isOpenAccess: true,
    topics: ["CRISPR-Cas9", "Gene Editing", "Molecular Biology", "Nobel Prize"],
  },
  {
    id: "lm_alphafold_nature_2021",
    title: "Highly Accurate Protein Structure Prediction with AlphaFold",
    authors: ["John Jumper", "Richard Evans", "Alexander Pritzel", "Demis Hassabis"],
    year: 2021,
    venue: "Nature",
    abstract: "Here we present AlphaFold, a computational method that can regularly predict protein structures with atomic accuracy - solving a 50-year-old grand challenge in computational biology.",
    citationCount: 28900,
    source: "PubMed",
    doi: "10.1038/s41586-021-03819-2",
    url: "https://doi.org/10.1038/s41586-021-03819-2",
    pdfUrl: "https://www.nature.com/articles/s41586-021-03819-2.pdf",
    isOpenAccess: true,
    topics: ["AlphaFold", "Structural Biology", "Protein Folding", "DeepMind"],
  },

  // 4. Physics & Astronomy
  {
    id: "lm_gravitational_waves_prl_2016",
    title: "Observation of Gravitational Waves from a Binary Black Hole Merger",
    authors: ["B. P. Abbott et al. (LIGO Scientific Collaboration and Virgo Collaboration)"],
    year: 2016,
    venue: "Physical Review Letters (PRL)",
    abstract: "On September 14, 2015, the Advanced LIGO detectors observed a transient gravitational-wave signal from the inspiral and merger of a pair of black holes and the ringdown of the resulting single black hole.",
    citationCount: 19800,
    source: "OpenAlex",
    doi: "10.1103/PhysRevLett.116.061102",
    url: "https://doi.org/10.1103/PhysRevLett.116.061102",
    isOpenAccess: true,
    topics: ["Gravitational Waves", "General Relativity", "Astrophysics", "Black Holes"],
  },
  {
    id: "lm_higgs_boson_plb_2012",
    title: "Observation of a new particle in the search for the Standard Model Higgs boson with the ATLAS detector at the LHC",
    authors: ["G. Aad et al. (ATLAS Collaboration)"],
    year: 2012,
    venue: "Physics Letters B",
    abstract: "A search for the Standard Model Higgs boson in proton-proton collisions with the ATLAS detector at the LHC is presented. A clear excess of events is observed at $m_H \\approx 126.0$ GeV with a local significance of $5.9\\sigma$.",
    citationCount: 16400,
    source: "Crossref",
    doi: "10.1016/j.physletb.2012.08.020",
    url: "https://doi.org/10.1016/j.physletb.2012.08.020",
    isOpenAccess: true,
    topics: ["Higgs Boson", "Particle Physics", "CERN LHC", "Standard Model"],
  },

  // 5. Chemistry & Materials Science
  {
    id: "lm_graphene_science_2004",
    title: "Electric Field Effect in Atomically Thin Carbon Films",
    authors: ["K. S. Novoselov", "A. K. Geim", "S. V. Morozov", "D. Jiang", "Y. Zhang", "S. V. Dubonos", "I. V. Grigorieva", "A. A. Firsov"],
    year: 2004,
    venue: "Science",
    abstract: "We describe monocrystalline graphitic films, which are a few atoms thick but are nonetheless stable under ambient conditions, metallic, and of remarkably high quality.",
    citationCount: 48500,
    source: "Semantic Scholar",
    doi: "10.1126/science.1102896",
    url: "https://doi.org/10.1126/science.1102896",
    isOpenAccess: true,
    topics: ["Graphene", "2D Materials", "Condensed Matter", "Nobel Prize"],
  },

  // 6. Economics, Business & Finance
  {
    id: "lm_prospect_theory_kahneman_1979",
    title: "Prospect Theory: An Analysis of Decision under Risk",
    authors: ["Daniel Kahneman", "Amos Tversky"],
    year: 1979,
    venue: "Econometrica",
    abstract: "This paper presents a critique of expected utility theory as a descriptive model of decision making under risk, and develops an alternative model, called prospect theory. Decisions are framed around reference points rather than final wealth states.",
    citationCount: 78500,
    source: "OpenAlex",
    doi: "10.2307/1914185",
    url: "https://doi.org/10.2307/1914185",
    isOpenAccess: true,
    topics: ["Prospect Theory", "Behavioral Economics", "Loss Aversion", "Decision Science"],
  },

  // 7. Psychology & Neuroscience
  {
    id: "lm_default_mode_network_2001",
    title: "A Default Mode of Brain Function",
    authors: ["Marcus E. Raichle", "Ann Mary MacLeod", "Abraham Z. Snyder", "William J. Powers", "David A. Gusnard", "Gordon L. Shulman"],
    year: 2001,
    venue: "Proceedings of the National Academy of Sciences (PNAS)",
    abstract: "A baseline or default state of the brain is recognized in cognitive neuroimaging. During rest, specific interconnected brain networks exhibit high metabolic activity and functional connectivity.",
    citationCount: 24300,
    source: "PubMed",
    doi: "10.1073/pnas.98.2.676",
    url: "https://doi.org/10.1073/pnas.98.2.676",
    isOpenAccess: true,
    topics: ["Default Mode Network", "fMRI Neuroimaging", "Cognitive Neuroscience", "Brain Connectivity"],
  },

  // 8. Climate & Earth Sciences
  {
    id: "lm_ipcc_tipping_points_nature_2019",
    title: "Climate Tipping Points - Too Risky to Bet Against",
    authors: ["Timothy M. Lenton", "Johan Rockstrom", "Owen Gaffney", "Stefan Rahmstorf", "Katherine Richardson", "Will Steffen", "Hans Joachim Schellnhuber"],
    year: 2019,
    venue: "Nature",
    abstract: "Politicians, economists and even some natural scientists have tended to assume that tipping points in the Earth system - such as the loss of the Amazon rainforest or the West Antarctic ice sheet - are of low probability. Growing evidence suggests they could be exceeded by warming of 1.5 to 2C.",
    citationCount: 6500,
    source: "Europe PMC",
    doi: "10.1038/d41586-019-03595-0",
    url: "https://doi.org/10.1038/d41586-019-03595-0",
    isOpenAccess: true,
    topics: ["Climate Tipping Points", "Earth Systems", "AMOC", "Global Warming"],
  },

  // 9. Mathematics & Statistics
  {
    id: "lm_wasserstein_wgan_2017",
    title: "Wasserstein GAN",
    authors: ["Martin Arjovsky", "Soumith Chintala", "Léon Bottou"],
    year: 2017,
    venue: "International Conference on Machine Learning (ICML)",
    abstract: "We introduce a new algorithm which provides an alternative to traditional GAN training. In this new model, we show that we can improve the stability of learning, balance the discriminator/generator, and provide meaningful learning curves using the Earth Mover's (Wasserstein-1) distance.",
    citationCount: 22100,
    source: "arXiv",
    doi: "10.48550/arXiv.1701.07875",
    url: "https://arxiv.org/abs/1701.07875",
    pdfUrl: "https://arxiv.org/pdf/1701.07875.pdf",
    isOpenAccess: true,
    topics: ["Wasserstein Distance", "Optimal Transport", "Generative Models", "Probability Theory"],
  },

  // 10. Philosophy & Ethics
  {
    id: "lm_turing_computing_machinery_1950",
    title: "Computing Machinery and Intelligence",
    authors: ["Alan M. Turing"],
    year: 1950,
    venue: "Mind",
    abstract: "I propose to consider the question, 'Can machines think?' This should begin with definitions of the meaning of the terms 'machine' and 'think'. The imitation game (Turing Test) is proposed to operationalize machine intelligence.",
    citationCount: 46700,
    source: "OpenAlex",
    doi: "10.1093/mind/LIX.236.433",
    url: "https://doi.org/10.1093/mind/LIX.236.433",
    isOpenAccess: true,
    topics: ["Turing Test", "Philosophy of Mind", "Artificial Intelligence", "Epistemology"],
  },
];
